In [1]:
# Artificial Neural Network using keras 

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

# Importing other lib
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Part 1 - Data Preprocessing
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [3]:
y.value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [4]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [5]:
#Create dummy variables
geography=pd.get_dummies(X["Geography"],drop_first=True)
gender=pd.get_dummies(X['Gender'],drop_first=True)

## Concatenate the Data Frames

X=pd.concat([X,geography,gender],axis=1)

## Drop Unnecessary columns
X=X.drop(['Geography','Gender'],axis=1)


In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [7]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
# Initialising the ANN
classifier = Sequential()

In [9]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, activation='relu',input_dim = 11))

In [10]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, activation='relu'))
# Adding the output layer
classifier.add(Dense(units = 1, activation = 'sigmoid'))

In [11]:
# Compiling the ANN
classifier.compile(optimizer = 'Adamax', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [12]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train,validation_split=0.33, batch_size = 10, epochs = 10)


Epoch 1/10
536/536 [==============================] - 1s 696us/step - loss: 0.6197 - accuracy: 0.7009 - val_loss: 0.5349 - val_accuracy: 0.7955
Epoch 2/10
536/536 [==============================] - 0s 526us/step - loss: 0.5192 - accuracy: 0.7962 - val_loss: 0.5041 - val_accuracy: 0.7955
Epoch 3/10
536/536 [==============================] - 0s 519us/step - loss: 0.4989 - accuracy: 0.7962 - val_loss: 0.4911 - val_accuracy: 0.7955
Epoch 4/10
536/536 [==============================] - 0s 519us/step - loss: 0.4863 - accuracy: 0.7962 - val_loss: 0.4803 - val_accuracy: 0.7955
Epoch 5/10
536/536 [==============================] - 0s 515us/step - loss: 0.4752 - accuracy: 0.7957 - val_loss: 0.4709 - val_accuracy: 0.7959
Epoch 6/10
536/536 [==============================] - 0s 516us/step - loss: 0.4650 - accuracy: 0.7964 - val_loss: 0.4622 - val_accuracy: 0.7989
Epoch 7/10
536/536 [==============================] - 0s 519us/step - loss: 0.4556 - accuracy: 0.8003 - val_loss: 0.4541 - val_accuracy:

In [13]:
# Part 3 - Making the predictions and evaluating the model
# Predicting the Test set results
y_pred = classifier.predict(X_test)

63/63 [==============================] - 0s 337us/step


In [14]:
y_pred_proba = classifier.predict_proba(X_test)

AttributeError: 'Sequential' object has no attribute 'predict_proba'

In [15]:
y_pred

array([[0.31265783],
       [0.36195353],
       [0.12526037],
       ...,
       [0.19817719],
       [0.1863012 ],
       [0.3607248 ]], dtype=float32)

In [16]:
y_pred = (y_pred > 0.5)

In [17]:
unique, counts = np.unique(y_pred, return_counts=True)

In [18]:
unique

array([False,  True])

In [19]:
counts

array([1877,  123])

In [20]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])